### ISSUE TITLE
CSS display issue?

### ISSUE THREAD

**Issue by Mr-Sheep** [FriendsOfFlarum/reactions#48] opened 2021-09-14 13:55 UTC
When enabling this extension on Flarum v1.0.4, the reaction banner isn't located where it's supposed to be.

<img width="792" alt="Screen Shot 2021-09-14 at 9 46 24 PM" src="https://user-images.githubusercontent.com/24599209/133270663-01c04382-c8f1-487c-86e2-c375d693b2d6.png">

**Comment by datitisev** [comment] 2021-09-14 23:47
This is caused by gamification. But should be able to get fixed here.

**Comment by Mr-Sheep** [comment] 2021-09-14 23:53
I c. I have noticed that the reaction banner worked properly in the first post of a discussion

![IMG_C9FFF56DCBE0-1](https://user-images.githubusercontent.com/24599209/133348773-85685e58-2c7d-4b63-9a1e-802325593a6d.jpeg)

**Comment by Mr-Sheep** [comment] 2021-09-14 23:53
I c. I have noticed that the reaction banner worked properly in the first post of a discussion

![IMG_C9FFF56DCBE0-1](https://user-images.githubusercontent.com/24599209/133348773-85685e58-2c7d-4b63-9a1e-802325593a6d.jpeg)

**Comment by datitisev** [comment] 2021-09-14 23:58
Fixed in v1.0.2 🙂

**Closed** 2021-09-14 23:58 UTC
